name: Follow 25 Users

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: pip install selenium

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: latest

      - name: Run bot
        env:
          IG_USER: ${{ secrets.IG_USER }}
          IG_PASS: ${{ secrets.IG_PASS }}
        run: python3 testings.py

      - name: Commit updated seguidores_messi_243.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "bot@users.noreply.github.com"
          git add seguidores_messi_243.txt
          git commit -m "Update seguidores file" || echo "No changes to commit"
          git push
